### ISSUE TITLE
Port for others versions? (1.16-1.19)

### ISSUE THREAD

**Issue by seriousfreezing** [axialeaa/BlockyBubbles#1]
Please! Is for my modpack!

**Comment by axialeaa** [comment]
thanks for the suggestion! i have long-distance plans for multi-version scheming, but it's not on the immediate roadmap i'm afraid. i'll see what i can do when the time comes :)

**Comment by axialeaa** [comment]
i'll leave this report open to save duplicate requests, and to remind me to look into it in the future

**Comment by seriousfreezing** [comment]
Know that I'll be looking forward to updates. This is the only mod that changes the particle structure and brings it closer to the Bedrock way.
But for now I'll add your mod to my modpack :D

**Comment by axialeaa** [comment]
amazing! thanks for the support; that means a lot <3

**Comment by axialeaa** [comment]
look out for update 1.1.0, coming soon ;)
