### ISSUE TITLE
request: Blocky Guardians Bubbles

### ISSUE THREAD

**Issue by peow** [axialeaa/BlockyBubbles#2]
in an Ocean Monument, Guardians produce a lot of bubbles, even though the particles are set to "Decreased", which causes a large loss of FPS, it would be very interesting if your mod also changed these particles

![2024-02-25_18 47 29](https://github.com/axialeaa/BlockyBubbles/assets/105888751/891c818b-d4bf-43a0-a634-3d00971dd769)

If possible, I would like to ask for an update to fabric 1.20.1, with support for fabric loader 0.14.22, thank you

**Comment by axialeaa** [comment]
This is an interesting suggestion, but outside of the scope of this mod I'm afraid. Unlike bubble columns, guardian bubbles are not blocks and therefore would require a different approach--maybe one that is equally as laggy. Secondly, Blocky Bubbles exists for the sake of Bedrock parity. I'm not intending on adding features within it that don't exist on Bedrock Edition, for that reason :)

 If you want to disable the particles completely (I empathise with your point btw; they're a lot!) [Sodium Extra](https://modrinth.com/mod/sodium-extra) features the ability to turn off the rendering of individual particles in the game. These bubbles in particular are under the generic "bubble" toggle, which also affects things like mobs splashing, fishing bobbers bobbing, projectiles being shot and fish swimming.

Sorry I can't give a better answer than this. Thanks for downloading this mod, and I hope you find a solution that works!

**Comment by peow** [comment]
thank you for responding, I completely understand

**Comment by axialeaa** [comment]
My pleasure :)
