### ISSUE TITLE
Mixin Plugin is causing crash

### ISSUE THREAD

**Issue by Smartin-b** [axialeaa/BlockyBubbles#4]
The MixinPlugin is Loading the Main Mod class, this is causing a class load chain prior to the intended class loading.
![grafik](https://github.com/user-attachments/assets/5bb373ef-b52e-4b04-a48e-30675a256466)
The class load is triggered by this line
https://github.com/axialeaa/BlockyBubbles/blob/97509fa056cbc97d471dcba645f17b744db2a6b2/src/main/java/com/axialeaa/blockybubbles/BlockyBubblesMixinPlugin.java#L14
either remove the check for sodium loaded,
or allow the mixin to fail and remove the plugin alltogether
or move the soidum loaded check to the mixin class itself instead of calling the main class

**Comment by Smartin-b** [comment]
This crash can be observed when combined with Truly Modular, as Truly Modular has a Mixin in Minecrafts Text.class, and this class gets preloaded by this classloadchain, causing a crash.

**Comment by axialeaa** [comment]
thanks for reporting! keep an eye out for 1.2.1 soon
