### ISSUE TITLE
[Question] Usage in Modpacks

### ISSUE THREAD

**Issue by NXTler** [axialeaa/BlockyBubbles#8]
Greetings,
I'm currently working on a VulkanMod based performance Modpack and would like to include this particular mod as well. However, I haven't found any information about the usage in Modpacks in the description.
What am I allowed to do?

**Comment by axialeaa** [comment]
hey! using it in a modpack is fine by me as long as you include credit. putting mod menu in the pack is sufficient since my name will appear in the mod list there :)

**Comment by NXTler** [comment]
Thanks a lot for the information. I planned to credit all mod creators in the description of my modpack and I will post the Modrinth link here once it's finished.

**Comment by axialeaa** [comment]
thank you! :3

**Comment by NXTler** [comment]
Here is the modpack, it's unlisted for now as it still needs some testing: https://modrinth.com/modpack/vulkanic-optimizations

**Comment by axialeaa** [comment]
wonderful! looks great, thanks for the update :)
